### ISSUE TITLE
Chat screen needs to scroll to bottom upon new sent or received message

### ISSUE THREAD

**Issue by UrgeyBergy** [DenioD/SilentDragonLite-1#90]
Currently once a new message is sent you have to scroll down to see it, having the feed auto-scroll to bottom would benefit ease of use :)

**Comment by oDinZu** [comment]
There is definitely lag for sender screen after message sent, plus on first confirmation, the screen resets again. I enabled focusPolicy &quot;StrongFocus&quot; and this enables use of the Home, End and other keys to scroll with.

Since the lag between sending / receiving; we must have a statement that checks to observe if a message has been sent or received. After the message appears, then scroll to bottom (END button) or MAX with Scrollbar method.

https://doc.qt.io/qt-5/qabstractslider.html#SliderAction-enum

I don't understand why a message lags between sending message locally. It should be visible on screen almost instantaneous locally speaking; maybe encryption causes the lag.

After message finally appears on screen, we scroll to most recent message bubble with 0 confirmation. 

Then when 1 confirmation is notarized, the screen resets and scrollbar is messed up. Meaning, if we even do auto scroll to most recent message after submit, the screen will reset and we will have to scroll to most recent message again.

**Comment by DenioD** [comment]
This issue should be resolved with https://github.com/DenioD/SilentDragonLite-1/commit/72357dfc17dfc65196c66b4908767197bc45c437
